[package]
name = "nft_marketplace"
version = "0.1.1"
edition = "2023_01"
cairo-version = "2.5.4"

[dependencies]
starknet = "2.5.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git ", tag = "v0.10.0" }

[lib]

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
